DROP TABLE IF EXISTS HIVESTUDENTS;
CREATE EXTERNAL TABLE HIVESTUDENTS
(
    ID VARCHAR(24),
    NAME VARCHAR(24),
    STREET VARCHAR(256),
    ZIPCODE INT,
    STATE VARCHAR(20),
    PERCENTAGE DECIMAL
)
ROW FORMAT DELIMITED FIELDS
TERMINATED BY ','
STORED AS TEXTFILE LOCATION "/drill/testdata/information-schema/students/";

CREATE DATABASE IF NOT EXISTS MARKETING;
USE MARKETING;
CREATE TABLE IF NOT EXISTS MKT1 (COL1 STRING);
